package com.cmrx.bean;

public class SqlEnum {
	/*首页三个串并信息*/
	public static final String SelDepartmentCase = "SELECT departmentNum,accord,createTime,uploadUser,count(departmentNum) as dcount from Departmentcaseinfo where dataType=1";
	/*综合串并信息*/
	public static final String zonghe ="select count(*) from foms.syntheticalcaseinfo where (footnum is not null and dnanum is not null) or (footnum is not null and fingernum is not null) or (fingernum is not null and dnanum is not null)"; 
	
	/*首页-最新公告*/
	public static final String SelNewsIndex = "select * from (select t.*,rownum rn from (select newsId,newsTitle,newstype from news order by createDate desc) t where rownum<=6) where rn>=1";
	/*newsinformation*/
	//public static final String newsinformation="select news.newsId as id,news.newsTitle as title,news.newsContent as content,news.newstype as type,userinfo.truename as releasename,news.createDate as releasedate from news LEFT JOIN userinfo on news.createuserid=userinfo.userId";
	public static final String newsinformation="select newsId,new" +
			"sTitle,newsContent,newstype,truename,createDate from news LEFT JOIN userinfo on news.createuserid=userinfo.userId";
	//事件列表
	public static final String scenceinvestigation="select investigation_no,investigation_place,protector,occurrence_date_from,investigation_date_from from scene_investigation";
	//时间轴
	public static final String scenceinvestigationtimebase="select to_char(RECEIVED_DATE, 'yyyy-MM-dd HH12:MI:SS') as RECEIVED_DATE,to_char(DISPATCH_DATE, 'yyyy-MM-dd HH12:MI:SS') as DISPATCH_DATE,to_char(OCCURRENCE_DATE_TO, 'yyyy-MM-dd HH12:MI:SS') as OCCURRENCE_DATE_TO,to_char(NOTE_MADE_DATE, 'yyyy-MM-dd HH12:MI:SS') as NOTE_MADE_DATE,to_char(PROTECTION_DATE, 'yyyy-MM-dd HH12:MI:SS') as PROTECTION_DATE,to_char(OCCURRENCE_DATE_FROM, 'yyyy-MM-dd HH12:MI:SS') as OCCURRENCE_DATE_FROM,to_char(INVESTIGATION_DATE_TO, 'yyyy-MM-dd HH12:MI:SS') as INVESTIGATION_DATE_TO,to_char(TRANSFER_DATE, 'yyyy-MM-dd HH12:MI:SS') as TRANSFER_DATE,to_char(INVESTIGATION_DATE_FROM, 'yyyy-MM-dd HH12:MI:SS') as INVESTIGATION_DATE_FROM from scene_investigation";
	//现场勘验
	public static final String DepartmentZongHeFindCity="select dict_level,dict_key,dict_value,dict_sort from foms.sys_dict where root_key='XZQHDM' and parent_key='XZQHDM' or parent_key='370000'";
	//案件性质的列表
	public static final String DepartmentZongAnjainxingzhi="select kid as id,parent_key,text,(select count(*)from sys_dict where ROOT_KEY = \'AJLBDM\' and PARENT_KEY = kid) as isparent from (select DICT_KEY as kid, PARENT_KEY, DICT_VALUE as text from sys_dict where ROOT_KEY = \'AJLBDM\' order by DICT_SORT) t";
	//案件起数所有的
	public static final String DepartmentZongAnjianxingzhidalei="select * from foms.sys_dict where root_key=\'AJLBDM\' and parent_key=\'AJLBDM\'";
	//案件起数所有的
	public static final String DepartmentZongHeFindCityall="select sum(decode(substr(inv.init_server_no, 0, 4), '3705', 1, 0)) as a0,sum(decode(substr(inv.init_server_no, 0, 4), '3706', 1, 0)) as a1,sum(decode(substr(inv.init_server_no, 0, 4), '3707', 1, 0)) as a2,sum(decode(substr(inv.init_server_no, 0, 4), '3708', 1, 0)) as a3,sum(decode(substr(inv.init_server_no, 0, 4), '3709', 1, 0)) as a4,sum(decode(substr(inv.init_server_no, 0, 4), '3710', 1, 0)) as a5,sum(decode(substr(inv.init_server_no, 0, 4), '3711', 1, 0)) as a6,sum(decode(substr(inv.init_server_no, 0, 4), '3712', 1, 0)) as a7,sum(decode(substr(inv.init_server_no, 0, 4), '3713', 1, 0)) as a8,sum(decode(substr(inv.init_server_no, 0, 4), '3714', 1, 0)) as a9,sum(decode(substr(inv.init_server_no, 0, 4), '3715', 1, 0)) as a10,sum(decode(substr(inv.init_server_no, 0, 4), '3716', 1, 0)) as a11,sum(decode(substr(inv.init_server_no, 0, 4), '3717', 1, 0)) as a12,sum(decode(substr(inv.init_server_no, 0, 4), '3701', 1, 0)) as a13,sum(decode(substr(inv.init_server_no, 0, 4), '3702', 1, 0)) as a14,sum(decode(substr(inv.init_server_no, 0, 4), '3703', 1, 0)) as a15,sum(decode(substr(inv.init_server_no, 0, 4), '3704', 1, 0)) as a16 from foms.scene_investigation inv  where  (substr(inv.init_server_no, 0, 4) = '3705' or substr(inv.init_server_no, 0, 4) = '3706' or substr(inv.init_server_no, 0, 4) = '3707' or substr(inv.init_server_no, 0, 4) = '3708' or substr(inv.init_server_no, 0, 4) = '3709' or substr(inv.init_server_no, 0, 4) = '3710' or substr(inv.init_server_no, 0, 4) = '3711' or substr(inv.init_server_no, 0, 4) = '3712' or substr(inv.init_server_no, 0, 4) = '3713' or substr(inv.init_server_no, 0, 4) = '3714' or substr(inv.init_server_no, 0, 4) = '3715' or substr(inv.init_server_no, 0, 4) = '3716' or substr(inv.init_server_no, 0, 4) = '3717' or substr(inv.init_server_no, 0, 4) = '3701' or substr(inv.init_server_no, 0, 4) = '3702' or substr(inv.init_server_no, 0, 4) = '3703' or substr(inv.init_server_no, 0, 4) = '3704')";
	//查询所有的城市
	public static final String DepartmentZongHeFindCityAllData="select dict_key, dict_value from foms.sys_dict where root_key = \'XZQHDM\' and parent_key = \'XZQHDM\' and substr(dict_key,0,6)!=\'370000\' or parent_key = \'370000\' order by dict_key";
	//查询所有的城市包含省份
	public static final String DepartmentZongHeFindCityAllProvinceData="select dict_key, dict_value from foms.sys_dict where root_key = \'XZQHDM\' and parent_key = \'XZQHDM\' or parent_key = \'370000\' order by  dict_key";
	//查询所有的案件性质
	public static final String DepartmentZongHeFindAnJianXingZhi="select dict_value,root_key,parent_key,dict_key from foms.sys_dict where root_key=\'AJLBDM\' and parent_key=\'AJLBDM\'";
	/*private String RECEIVED_DATE;//接警时间
	private String DISPATCH_DATE;//出警时间
	private String OCCURRENCE_DATE_FROM;//发案时间起
	private String OCCURRENCE_DATE_TO;//发案时间止
	private String NOTE_MADE_DATE;//制作笔录时间
	private String PROTECTION_DATE;//现场保护时间
	private String TRANSFER_DATE;//信息上报时间
	private String INVESTIGATION_DATE_FROM;//勘验开始时间
	private String INVESTIGATION_DATE_TO;//勘验结束时间
*/	
//查询所有的城市的足迹的起数
	//public static final String DepartmentZongHeFindZuJiQiShu="select sum(decode(substr(deptid,0,4),'3701',1,0)) as a0,sum(decode(substr(deptid,0,4),'3702',1,0)) as a1,sum(decode(substr(deptid,0,4),'3703',1,0)) as a2,sum(decode(substr(deptid,0,4),'3704',1,0)) as a3,sum(decode(substr(deptid,0,4),'3705',1,0)) as a4,sum(decode(substr(deptid,0,4),'3706',1,0)) as a5,sum(decode(substr(deptid,0,4),'3707',1,0)) as a6,sum(decode(substr(deptid,0,4),'3708',1,0)) as a7,sum(decode(substr(deptid,0,4),'3709',1,0)) as a8,sum(decode(substr(deptid,0,4),'3710',1,0)) as a9,sum(decode(substr(deptid,0,4),'3711',1,0)) as a10,sum(decode(substr(deptid,0,4),'3712',1,0)) as a11,sum(decode(substr(deptid,0,4),'3713',1,0)) as a12,sum(decode(substr(deptid,0,4),'3714',1,0)) as a13,sum(decode(substr(deptid,0,4),'3715',1,0)) as a14,sum(decode(substr(deptid,0,4),'3716',1,0)) as a15,sum(decode(substr(deptid,0,4),'3717',1,0)) as a16 from (select base.deptid,base.inputtime,(select count(*) from foms.fais_sercapic pic where pic.sercaid=base.sercaid) counts from  foms.fais_sercabase base) base where(  substr(deptid,0,4)='3701' or substr(deptid,0,4)='3702' or substr(deptid,0,4)='3703' or substr(deptid,0,4)='3704' or substr(deptid,0,4)='3705' or substr(deptid,0,4)='3706' or substr(deptid,0,4)='3707' or substr(deptid,0,4)='3708' or substr(deptid,0,4)='3709' or substr(deptid,0,4)='3710' or substr(deptid,0,4)='3711' or substr(deptid,0,4)='3712' or substr(deptid,0,4)='3713' or substr(deptid,0,4)='3714' or substr(deptid,0,4)='3715' or substr(deptid,0,4)='3716' or substr(deptid,0,4)='3717') and inputtime>=to_date('2014-01-01 00:00:00','yyyy-mm-dd hh24:mi:ss') and inputtime<=to_date('2015-04-30 23:59:59','yyyy-mm-dd hh24:mi:ss')";
//查询所有的城市的足迹的起数
	public static final String DepartmentZongHeFindZuJiQiShu=" select sum(decode(substr(deptid,0,4),'3701',counts,0)) as a0,sum(decode(substr(deptid,0,4),'3702',counts,0)) as a1,sum(decode(substr(deptid,0,4),'3703',counts,0)) as a2,sum(decode(substr(deptid,0,4),'3704',counts,0)) as a3,sum(decode(substr(deptid,0,4),'3705',counts,0)) as a4,sum(decode(substr(deptid,0,4),'3706',counts,0)) as a5,sum(decode(substr(deptid,0,4),'3707',counts,0)) as a6,sum(decode(substr(deptid,0,4),'3708',counts,0)) as a7,sum(decode(substr(deptid,0,4),'3709',counts,0)) as a8,sum(decode(substr(deptid,0,4),'3710',counts,0)) as a9,sum(decode(substr(deptid,0,4),'3711',counts,0)) as a10,sum(decode(substr(deptid,0,4),'3712',counts,0)) as a11,sum(decode(substr(deptid,0,4),'3713',counts,0)) as a12,sum(decode(substr(deptid,0,4),'3714',counts,0)) as a13,sum(decode(substr(deptid,0,4),'3715',counts,0)) as a14,sum(decode(substr(deptid,0,4),'3716',counts,0)) as a15,sum(decode(substr(deptid,0,4),'3717',counts,0)) as a16 from (select base.deptid,base.inputtime,(select count(*) from foms.fais_sercapic pic where pic.sercaid=base.sercaid) counts from  foms.fais_sercabase base) base where(  substr(deptid,0,4)='3701' or substr(deptid,0,4)='3702' or substr(deptid,0,4)='3703' or substr(deptid,0,4)='3704' or substr(deptid,0,4)='3705' or substr(deptid,0,4)='3706' or substr(deptid,0,4)='3707' or substr(deptid,0,4)='3708' or substr(deptid,0,4)='3709' or substr(deptid,0,4)='3710' or substr(deptid,0,4)='3711' or substr(deptid,0,4)='3712' or substr(deptid,0,4)='3713' or substr(deptid,0,4)='3714' or substr(deptid,0,4)='3715' or substr(deptid,0,4)='3716' or substr(deptid,0,4)='3717')";
	//查询所有的dna信息
/*	public static final String DepartmentZongHeFinddnaInfo="select (select y.dict_value from (select dict_key, dict_value from foms.sys_dict where root_key = 'XZQHDM' and parent_key = 'XZQHDM'  and substr(dict_key, 0, 6) != '370000' or parent_key = '370000' order by dict_key ) y where dict_key = src_lab_regionalism) as DICT_VALUE,src_lab_regionalism as dict_key, count(*) chuanshu, sum((select count(*) from foms.dna_notification where src_case_id = dna_serialbase.scaseid)) as qishu from foms.dna_serialbase where (substr(src_lab_regionalism, 0, 4) = '3701' or  substr(src_lab_regionalism, 0, 4) = '3702' or  substr(src_lab_regionalism, 0, 4) = '3703' or  substr(src_lab_regionalism, 0, 4) = '3704' or  substr(src_lab_regionalism, 0, 4) = '3705' or  substr(src_lab_regionalism, 0, 4) = '3706' or  substr(src_lab_regionalism, 0, 4) = '3707' or  substr(src_lab_regionalism, 0, 4) = '3708' or  substr(src_lab_regionalism, 0, 4) = '3709' or  substr(src_lab_regionalism, 0, 4) = '3710' or  substr(src_lab_regionalism, 0, 4) = '3711' or  substr(src_lab_regionalism, 0, 4) = '3712' or  substr(src_lab_regionalism, 0, 4) = '3713' or  substr(src_lab_regionalism, 0, 4) = '3714' or  substr(src_lab_regionalism, 0, 4) = '3715' or  substr(src_lab_regionalism, 0, 4) = '3716' or substr(src_lab_regionalism, 0, 4) = '3717')  group by src_lab_regionalism";
*/	
	//查询所有的城市的足迹的串数
	public static final String DepartmentZongHeFindZuJiChuanShu="select sum(decode(substr(deptid,0,4),'3701',1,0)) as a0,sum(decode(substr(deptid,0,4),'3702',1,0)) as a1,sum(decode(substr(deptid,0,4),'3703',1,0)) as a2,sum(decode(substr(deptid,0,4),'3704',1,0)) as a3,sum(decode(substr(deptid,0,4),'3705',1,0)) as a4,sum(decode(substr(deptid,0,4),'3706',1,0)) as a5,sum(decode(substr(deptid,0,4),'3707',1,0)) as a6,sum(decode(substr(deptid,0,4),'3708',1,0)) as a7,sum(decode(substr(deptid,0,4),'3709',1,0)) as a8,sum(decode(substr(deptid,0,4),'3710',1,0)) as a9,sum(decode(substr(deptid,0,4),'3711',1,0)) as a10,sum(decode(substr(deptid,0,4),'3712',1,0)) as a11,sum(decode(substr(deptid,0,4),'3713',1,0)) as a12,sum(decode(substr(deptid,0,4),'3714',1,0)) as a13,sum(decode(substr(deptid,0,4),'3715',1,0)) as a14,sum(decode(substr(deptid,0,4),'3716',1,0)) as a15,sum(decode(substr(deptid,0,4),'3717',1,0)) as a16 from (select base.deptid,base.inputtime from  foms.fais_sercabase base) base where(  substr(deptid,0,4)='3701' or substr(deptid,0,4)='3702' or substr(deptid,0,4)='3703' or substr(deptid,0,4)='3704' or substr(deptid,0,4)='3705' or substr(deptid,0,4)='3706' or substr(deptid,0,4)='3707' or substr(deptid,0,4)='3708' or substr(deptid,0,4)='3709' or substr(deptid,0,4)='3710' or substr(deptid,0,4)='3711' or substr(deptid,0,4)='3712' or substr(deptid,0,4)='3713' or substr(deptid,0,4)='3714' or substr(deptid,0,4)='3715' or substr(deptid,0,4)='3716' or substr(deptid,0,4)='3717')";

	/**
	 * 
	 * 查询dna的串数与起数
	 */
	public static final String DepartmentZongHeFinddnaInfo=" SELECT (SELECT DICT_VALUE FROM FOMS.SYS_DICT WHERE DICT_KEY = SRC_LAB_REGIONALISM) DICT_VALUE,COUNT(SRC_LAB_REGIONALISM) AS CHUANSHU, SUM((SELECT COUNT(SRC_CASE_ID)  FROM FOMS.DNA_NOTIFICATION  WHERE SRC_CASE_ID = DNA_SERIALBASE.SCASEID)) QISHU FROM DNA_SERIALBASE WHERE SRC_LAB_REGIONALISM > 0  AND SRC_LAB_REGIONALISM IN (SELECT DICT_KEY FROM FOMS.SYS_DICT WHERE PARENT_KEY = '370000') GROUP BY SRC_LAB_REGIONALISM";

}
